server:
  port: 8200

#默认使用配置
spring:
  profiles:
    active: dev

  security:
    user:
      name: admin
      password: admin

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

#redis配置参数
  redis:
    database: 0
    host: 193.112.142.183
    port: 6379
    password: '@w-(*102Y613}-Redis'
    lettuce:
      pool:
        max-active: 1000
        max-idle: 10
        min-idle: 5
        max-wait: -1
    timeout: 30000
# Thymeleaf 配置
  thymeleaf:
    cache: false
    prefix: classpath:/thymeleaf/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html

#token配置参数
token:
  #秘钥，放这里不安全未使用
  sha: token
  subject: subject
  #过期时间 token过期失效30*60*1000*2
  expires: 3600000
  header: Authorization
  name: token

logging:
  level:
    com.tgpms.web: debug

